import type { NavigationContent } from '../types';

const navigation: NavigationContent = {
  topBanner: {
    announcement: 'senhasegura is now Segura®!',
    linkText: 'Get to Know Our New Brand ›',
    linkUrl: '/new-brand.html',
  },
  topMenu: {
    becomePartner: 'Become a Partner',
    contact: 'Contact',
    support: 'Support',
    docs: 'Docs',
  },
  cta: {
    bookDemo: 'Book a Demo ›',
  },
  platform: {
    label: 'Platform',
    products: [
      { title: 'Secure Privileged Access', description: 'Discover, manage, protect, and audit privileged accounts and sessions.', href: '/products/privileged-access-management.html' },
      { title: 'Endpoint Privilege Management', description: 'Just-in-time and on-demand endpoint privilege management and elevation.', href: '/products/endpoint-privilege-manager.html' },
      { title: 'Multi-Cloud Identity Security', description: 'Secure access to cloud consoles and services across multi-cloud environments.', href: '/products/cloud-infrastructure-entitlements-management.html' },
      { title: 'DevOps Secrets Management', description: 'Secrets management for applications, databases, CI/CD tools, and services.', href: '/products/devops-secret-manager.html' },
      { title: 'Certificate Management', description: 'Full lifecycle certificate management, automation, and publishing.', href: '/products/certificate-manager.html' },
      { title: 'Privileged Remote Access', description: 'VPN-less granular remote access for your employees, vendors, and third parties.', href: '/products/domum-remote-access.html' },
      { title: 'Personal Password Manager', description: 'Securely store all of your personal passwords and sensitive data.', href: '/products/mysafe.html' },
      { title: 'Privileged Infrastructure', description: 'Appliance-based scalable high-availability infrastructure for heightened security.', href: '/products/privileged-infrastructure.html' },
    ],
    cta: {
      title: '360º Privilege Platform',
      description: 'A comprehensive, extensible platform that lets your ensure least privilege best practices and improve your security posture across the enterprise with the lowest cost of ownership and fastest deployment in the industry.',
      buttonText: 'Explore Products ›',
      href: '/products.html',
    },
  },
  solutions: {
    label: 'Solutions',
    byUseCase: {
      sectionTitle: 'By Use Case',
      items: [
        { label: 'Audit and Compliance', href: '/solutions/audit.html' },
        { label: 'Data Theft Prevention', href: '/solutions/data-theft-prevention.html' },
        { label: 'DevOps', href: '/solutions/devops.html' },
        { label: 'Insider Threat Elimination', href: '/solutions/insider-threat.html' },
        { label: 'Third Party & Remote Access', href: '/solutions/third-party-access.html' },
        { label: 'Privileged Access Recording', href: '/solutions/privileged-access-recording.html' },
        { label: 'Privilege Abuse', href: '/solutions/privilege-abuse.html' },
        { label: 'Hardcoded Passwords', href: '/solutions/hardcoded-password.html' },
      ],
    },
    useCaseColumn2: {
      sectionTitle: '',
      items: [
        { label: 'Password Reset', href: '/solutions/password-reset.html' },
        { label: 'Cyber Insurance', href: '/solutions/pam-for-cyber-insurance.html' },
        { label: 'Machine Identity', href: '/solutions/machine-identity.html' },
        { label: 'Identity Threat Detection and Response', href: '/solutions/identity-threat-detection-response-itdr.html' },
      ],
    },
    byIndustry: {
      sectionTitle: 'By Industry',
      items: [
        { label: 'Energy and Utilities', href: '/solutions/energy-and-utilities.html' },
        { label: 'Financial', href: '/solutions/financial.html' },
        { label: 'Government', href: '/solutions/government.html' },
        { label: 'Health Care', href: '/solutions/health-care.html' },
        { label: 'Legal', href: '/solutions/legal.html' },
        { label: 'Telecoms', href: '/solutions/telecoms.html' },
        { label: 'Retail', href: '/solutions/retail.html' },
      ],
    },
    byCertification: {
      sectionTitle: 'By Certification',
      items: [
        { label: 'PCI DSS', href: '/solutions/pci.html' },
        { label: 'SOX', href: '/solutions/sox.html' },
        { label: 'ISO 27001', href: '/solutions/iso-27001.html' },
        { label: 'HIPAA', href: '/solutions/hipaa.html' },
        { label: 'NIST', href: '/solutions/nist.html' },
        { label: 'GDPR', href: '/solutions/gdpr.html' },
        { label: 'ISA 62443 | 4.0', href: '/solutions/isa-iec-62443.html' },
        { label: 'SAMA', href: '/solutions/sama.html' },
        { label: 'KSA | NCA | NTC', href: '/solutions/ksa.html' },
      ],
    },
  },
  services: {
    label: 'Services',
  },
  partners: {
    label: 'Partners',
    affinityProgram: 'Affinity Partner Program',
    aboutProgram: 'About the Program',
    becomePartner: 'Become a Partner',
    seguraOnAzure: 'Segura® on Azure',
    partnersGroupLinkedIn: 'Partners Group on LinkedIn',
    opportunityBooking: 'Opportunity Booking',
    opportunityBookingDesc: 'For our Commercial Team to support your sale more effectively, request your opportunity booking here.',
    requestNow: 'Request Now >',
    seePartners: 'See our Partners',
    seePartnersDesc: 'We work with partners worldwide to deliver our leading solution to your organization.',
    findPartner: 'Find a partner ›',
  },
  services: {
    label: 'Services',
    deploymentAndConsulting: 'Deployment and Consulting',
    deploymentDesc: 'We and our partners offer professional services for the deployment of our solutions, including initial setup, customization, and consulting',
    exploreDeployment: 'Explore Deployment',
    solutionCenter: 'Solution Center',
    solutionCenterDesc: 'We offer award-winning support to all our customers. Find out about our support services and resources and how to contact our support here',
    exploreSolutionCenter: 'Explore Our Solution Center',
    training: 'Training',
    trainingDesc: 'Access guidelines, documentation, and videos to better understand our products and services on our e-learning portal',
    exploreTraining: 'Explore Training & Certifications',
  },
  company: {
    label: 'Company',
    aboutUs: 'About Us',
    meetSegura: 'Meet Segura®',
    careers: 'Careers',
    contactUs: 'Contact Us',
    buildWithUs: 'Build With Us',
    whySegura: 'Why Segura®',
    advantage: 'The Segura® advantage',
    pricing: 'Pricing',
    trustCenter: 'Trust Center',
    awards: 'Awards & Analyst coverage',
    mea: 'Segura® in the MEA',
    jiuJitCISO: 'Segura@ JiuJitCISO',
    news: 'News',
    inTheNews: 'Segura® in the News',
    pressRoom: 'Press Room',
    centersOfExcellence: 'Centers of Excellence',
    saoPaulo: 'São Paulo Headquarter',
    riyadh: 'Riyadh CoE',
    austin: 'Austin CoE',
    katowice: 'Katowice CoE',
    kualaLumpur: 'Kuala Lumpur CoE - SOON!',
    singapore: 'Singapore CoE - SOON!',
    manila: 'Manila CoE - SOON!',
    soon: 'SOON!',
  },
  resources: {
    label: 'Resources',
    productInfo: {
      sectionTitle: 'Product Information',
      docsLabel: 'Documentation',
      items: [
        { label: 'Datasheets', href: 'https://lp.senhasegura.co/EN/RICH-MATERIALS#datasheets' },
        { label: 'Architecture', href: '/services/product-architecture.html' },
        { label: 'Integrations', href: '/services/integration.html' },
        { label: 'Security', href: '/services/security.html' },
        { label: 'Customer Cases', href: '/customer-cases.html' },
      ],
    },
    cybersecurityInfo: {
      sectionTitle: 'Cybersecurity Information',
      items: [
        { label: 'Blog', href: '/blog.html' },
        { label: 'PAMaturity', href: '/pamaturity.html' },
        { label: 'Privileged Access Management 101', href: '/resources/ebook-pam-101.html' },
        { label: 'A Guide to Attack Surface Management', href: '/resources/ebook-reducing-your-cybersecurity-risk.html' },
        { label: 'Cloud Security: 5 Concerns', href: '/resources/infographic-cloud-security.html' },
        { label: "Gartner's 16 Metrics for Cyber Protection", href: '/resources/infographic-metrics-measure-organization-level-cyber-protection.html' },
        { label: 'PAM Implementation Costs', href: '/resources/whitepaper-total-cost-of-ownership.html' },
        { label: 'Identity Security Intelligence', href: '/resources/ebook-identity-security-intelligence.html' },
      ],
    },
    reports: {
      sectionTitle: 'Reports',
      items: [
        { label: 'Gartner Magic Quadrant Report 2025', href: '/company/gartner-pam-magic-quadrant-2025-report.html' },
        { label: 'SoftwareReviews Data Quadrant Report Privileged Access Management 2024', href: '/resources/report-buyer-experience-report-2024.html' },
        { label: 'KuppingerCole 2023 Leadership Compass Report for Privileged Access', href: 'https://lp.senhasegura.co/en/kuppingercole-leadership-compass-for-pam' },
        { label: 'Gartner Magic Quadrant for PAM 2021 Report', href: '/company/gartner-pam-magic-quadrant-2021-report.html' },
        { label: '2022 Frost & Sullivan Customer Value Leadership Award', href: '/company/frost-sullivan-2022-customer-value-award.html' },
      ],
    },
    legal: {
      sectionTitle: 'Legal and Licensing',
      items: [
        { label: 'Terms of Use', href: '/policies-and-terms/terms-of-service.html' },
        { label: 'End User License Agreement (EULA)', href: '/policies-and-terms/eula.html' },
        { label: 'Privacy and Cookies Policy', href: '/privacy-and-cookie-statement.html' },
        { label: 'Terms and Conditions', href: '/policies-and-terms/terms-and-general-conditions.html' },
        { label: 'Operations', href: '/company/operations.html' },
      ],
    },
  },
};

export default navigation;
