import type { NavigationContent } from '../types';

const navigation: NavigationContent = {
  topBanner: {
    announcement: 'A senhasegura agora é Segura®!',
    linkText: 'Conheça a nova marca ›',
    linkUrl: '/pt-br/nova-marca.html',
  },
  topMenu: {
    becomePartner: 'Seja um Parceiro',
    contact: 'Contato',
    support: 'Suporte',
    docs: 'Docs',
  },
  cta: {
    bookDemo: 'Pedir Demo ›',
  },
  platform: {
    label: 'Plataforma',
    products: [
      { title: 'Acesso Privilegiado Seguro', description: 'Descubra, gerencie, proteja e audite contas e sessões.', href: '/pt-br/produtos/privileged-access-management.html' },
      { title: 'Proteção de Endpoint & Dispositivos', description: 'Acesso Just In Time, gestão e elevação de privilégios sob demanda.', href: '/pt-br/produtos/endpoint-privilege-manager.html' },
      { title: 'Segurança de Identidades Multi-Cloud', description: 'Acesso seguro em consoles e serviços de múltiplos ambientes em nuvem.', href: '/pt-br/produtos/cloud-infrastructure-entitlements-management.html' },
      { title: 'Gerenciamento de segredos de DevOps', description: 'Gestão de secrets para aplicações, bancos de dados, ferramentas CI/CD e serviços.', href: '/pt-br/produtos/devops-secret-manager.html' },
      { title: 'Gestão de Certificados', description: 'Gestão de ciclo de vida completo de certificados, com automação e publicação.', href: '/pt-br/produtos/certificate-manager.html' },
      { title: 'Trabalho Remoto seguro', description: 'Acesso remoto sem VPN e com nível de acesso detalhado para seus colaboradores, fornecedores e terceiros.', href: '/pt-br/produtos/domum-remote-access.html' },
      { title: 'Gerenciador de Senhas Pessoais', description: 'Armazene com segurança suas senhas pessoais e dados sensíveis.', href: '/pt-br/produtos/mysafe.html' },
      { title: 'Infraestrutura Privilegiada', description: 'Infraestrutura ativa, segura, de alta disponibilidade e escalável.', href: '/pt-br/produtos/privileged-infrastructure.html' },
    ],
    cta: {
      title: 'Plataforma 360°',
      description: 'Uma plataforma completa, que garante as melhores práticas de Privilégio Mínimo e melhora a postura de segurança em toda a sua organização com o menor custo de propriedade total e implementação mais rápida do mercado.',
      buttonText: 'Explore Nossos Produtos',
      href: '/pt-br/produtos',
    },
  },
  solutions: {
    label: 'Soluções',
    byUseCase: {
      sectionTitle: 'Por Tipo de Uso',
      items: [
        { label: 'Auditoria e Compliance', href: '/pt-br/solucoes/audit.html' },
        { label: 'Prevenção a Roubo de Dados', href: '/pt-br/solucoes/data-theft-prevention.html' },
        { label: 'DevOps', href: '/pt-br/solucoes/devops.html' },
        { label: 'Eliminação de Ameaça Interna', href: '/pt-br/solucoes/insider-threat.html' },
        { label: 'Acesso Remoto e Terceiros', href: '/pt-br/solucoes/third-party-access.html' },
        { label: 'Gravação de Acesso Privilegiado', href: '/pt-br/solucoes/privileged-access-recording.html' },
        { label: 'Abuso de Privilégios', href: '/pt-br/solucoes/privilege-abuse.html' },
        { label: 'Senhas Hardcoded', href: '/pt-br/solucoes/hardcoded-password.html' },
      ],
    },
    useCaseColumn2: {
      sectionTitle: '',
      items: [
        { label: 'Redefinição de Senhas', href: '/pt-br/solucoes/password-reset.html' },
        { label: 'Seguro Cibernético', href: '/pt-br/solucoes/pam-for-cyber-insurance.html' },
        { label: 'Identidade de Máquina', href: '/pt-br/solucoes/machine-identity.html' },
        { label: 'Detecção e Resposta a Ameaças de Identidade (ITDR)', href: '/pt-br/solucoes/identity-threat-detection-response-itdr.html' },
      ],
    },
    byIndustry: {
      sectionTitle: 'Por Indústria',
      items: [
        { label: 'Energia e Infraestrutura', href: '/pt-br/solucoes/energy-and-utilities.html' },
        { label: 'Financeira', href: '/pt-br/solucoes/financial.html' },
        { label: 'Governamental', href: '/pt-br/solucoes/government.html' },
        { label: 'Saúde', href: '/pt-br/solucoes/health-care.html' },
        { label: 'Jurídico', href: '/pt-br/solucoes/legal.html' },
        { label: 'Telecomunicações', href: '/pt-br/solucoes/telecoms.html' },
        { label: 'Varejo', href: '/pt-br/solucoes/retail.html' },
      ],
    },
    byCertification: {
      sectionTitle: 'Por Certificação',
      items: [
        { label: 'PCI DSS', href: '/pt-br/solucoes/pci.html' },
        { label: 'SOX', href: '/pt-br/solucoes/sox.html' },
        { label: 'ISO 27001', href: '/pt-br/solucoes/iso-27001.html' },
        { label: 'HIPAA', href: '/pt-br/solucoes/hipaa.html' },
        { label: 'NIST', href: '/pt-br/solucoes/nist.html' },
        { label: 'LGPD', href: '/pt-br/solucoes/lgpd.html' },
        { label: 'ISO | 62443 | 4.0', href: '/pt-br/solucoes/isa-iec-62443.html' },
        { label: 'SAMA', href: '/pt-br/solucoes/sama.html' },
        { label: 'KSA | NCA | NTC', href: '/pt-br/solucoes/ksa.html' },
      ],
    },
  },
  services: {
    label: 'Serviços',
  },
  partners: {
    label: 'Parceiros',
    affinityProgram: 'Programa de Parceiros Affinity',
    aboutProgram: 'Sobre o Programa',
    becomePartner: 'Torne-se um parceiro',
    seguraOnAzure: 'Segura® no Azure',
    partnersGroupLinkedIn: 'Grupo de Parceiros no LinkedIn',
    opportunityBooking: 'Reserva de Oportunidade',
    opportunityBookingDesc: 'Para nossa equipe comercial apoiar sua venda de forma mais eficaz, solicite sua reserva de oportunidade aqui.',
    requestNow: 'Solicitar Agora >',
    seePartners: 'Veja nossos Parceiros',
    seePartnersDesc: 'Trabalhamos com parceiros em todo o mundo para entregar nossa solução líder à sua organização.',
    findPartner: 'Encontrar um parceiro ›',
  },
  services: {
    label: 'Serviços',
    deploymentAndConsulting: 'Implementação e Consultoria',
    deploymentDesc: 'Nós e nossos parceiros oferecemos serviços profissionais para a implementação de nossas soluções, incluindo configuração inicial, personalização e consultoria',
    exploreDeployment: 'Explorar Implementação',
    solutionCenter: 'Centro de Soluções',
    solutionCenterDesc: 'Oferecemos suporte premiado a todos os nossos clientes. Descubra nossos serviços de suporte e recursos e como entrar em contato com nosso suporte aqui',
    exploreSolutionCenter: 'Explorar nosso Centro de Soluções',
    training: 'Treinamento',
    trainingDesc: 'Acesse diretrizes, documentação e vídeos para entender melhor nossos produtos e serviços em nosso portal de e-learning',
    exploreTraining: 'Explorar Treinamento e Certificações',
  },
  company: {
    label: 'Empresa',
    aboutUs: 'Sobre nós',
    meetSegura: 'Conheça a Segura®',
    careers: 'Carreiras',
    contactUs: 'Fale Conosco',
    buildWithUs: 'Construa Conosco',
    whySegura: 'Por que Segura®',
    advantage: 'A vantagem Segura®',
    pricing: 'Preços',
    trustCenter: 'Centro de Confiança',
    awards: 'Prêmios e Cobertura de Analistas',
    mea: 'Segura® no MEA',
    jiuJitCISO: 'Segura@ JiuJitCISO',
    news: 'Notícias',
    inTheNews: 'Segura® nas Notícias',
    pressRoom: 'Sala de Imprensa',
    centersOfExcellence: 'Centros de Excelência',
    saoPaulo: 'Sede São Paulo',
    riyadh: 'CoE Riade',
    austin: 'CoE Austin',
    katowice: 'CoE Katowice',
    kualaLumpur: 'CoE Kuala Lumpur - EM BREVE!',
    singapore: 'CoE Singapura - EM BREVE!',
    manila: 'CoE Manila - EM BREVE!',
    soon: 'EM BREVE!',
  },
  resources: {
    label: 'Recursos',
    productInfo: {
      sectionTitle: 'Informações do Produto',
      docsLabel: 'Documentação',
      items: [
        { label: 'Datasheets', href: 'https://lp.senhasegura.co/PT/RICH-MATERIALS#datasheets' },
        { label: 'Arquitetura', href: '/pt-br/servicos/arquitetura-do-produto.html' },
        { label: 'Integrações', href: '/pt-br/servicos/integracao.html' },
        { label: 'Segurança', href: '/pt-br/servicos/seguranca.html' },
        { label: 'Casos de Cliente', href: '/pt-br/casos-de-cliente.html' },
      ],
    },
    cybersecurityInfo: {
      sectionTitle: 'Informações de Cibersegurança',
      items: [
        { label: 'Blog', href: '/pt-br/blog.html' },
        { label: 'PAMaturity', href: '/pt-br/pamaturity.html' },
        { label: 'Privileged Access Management 101', href: '/pt-br/recursos/ebook-pam-101.html' },
        { label: 'A Guide to Attack Surface Management', href: '/pt-br/recursos/ebook-reducing-your-cybersecurity-risk.html' },
        { label: 'Cloud Security: 5 Concerns', href: '/pt-br/recursos/infographic-cloud-security.html' },
        { label: "Gartner's 16 Metrics for Cyber Protection", href: '/pt-br/recursos/infographic-metrics-measure-organization-level-cyber-protection.html' },
        { label: 'PAM Implementation Costs', href: '/pt-br/recursos/whitepaper-total-cost-of-ownership.html' },
        { label: 'Identity Security Intelligence', href: '/pt-br/recursos/ebook-identity-security-intelligence.html' },
      ],
    },
    reports: {
      sectionTitle: 'Relatórios',
      items: [
        { label: 'Gartner Magic Quadrant Report 2025', href: '/pt-br/empresa/gartner-pam-magic-quadrant-2025-report.html' },
        { label: 'SoftwareReviews Data Quadrant Report Privileged Access Management 2024', href: '/pt-br/recursos/report-buyer-experience-report-2024.html' },
        { label: 'KuppingerCole 2023 Leadership Compass Report for Privileged Access', href: 'https://lp.senhasegura.co/pt/kuppingercole-leadership-compass-for-pam' },
        { label: 'Gartner Magic Quadrant for PAM 2021 Report', href: '/pt-br/empresa/gartner-pam-magic-quadrant-2021-report.html' },
        { label: '2022 Frost & Sullivan Customer Value Leadership Award', href: '/pt-br/empresa/frost-sullivan-2022-customer-value-award.html' },
      ],
    },
    legal: {
      sectionTitle: 'Legal e Licenciamento',
      items: [
        { label: 'Termos de Uso', href: '/pt-br/politicas-e-termos/terms-of-service.html' },
        { label: 'Contrato de Licença de Usuário Final (EULA)', href: '/pt-br/politicas-e-termos/eula.html' },
        { label: 'Política de Privacidade e Cookies', href: '/pt-br/privacy-and-cookie-statement.html' },
        { label: 'Termos e Condições', href: '/pt-br/politicas-e-termos/terms-and-general-conditions.html' },
        { label: 'Operações', href: '/pt-br/empresa/operations.html' },
      ],
    },
  },
};

export default navigation;
